version: '3.8'
services:
  login-db:
    image: postgres:latest
    container_name: login-db-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: login
    ports:
      - "5001:5432"
