version: '3.8'
services:
  person-db:
    image: postgres:latest
    container_name: person-db-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: person
    ports:
      - "5002:5432"
