version: '3.8'
services:
  person-db:
    image: mongo
    container_name: person-db-container
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - "27017:27017"
